name: cropped
description: "Cropped fit—shorter length with close chest."

aspects:
  chest:
    # Inherit core
    weight_multiplier: 1.0

  shoulder:
    # Inherit core

  length:
    # Subtract 2.0" from each length threshold
    cropped_min_offset: 0.0       # keep the same minimum for \"cropped\"
    short_max_offset: -1.0        # shorter maximum for \"short\"
    ideal_max_offset: -2.0        # ideal fit happens 2\" shorter than core

  hem:
    # Inherit core
    weight_multiplier: 1.0

  sleeve:
    # Inherit core

  weight:
    # Inherit core
    weight_multiplier: 1.0

interaction_adjustments:
  # No change
