name: slim
description: "Modern slim fit. Trimmer in chest and shoulder, less tolerance for oversized or relaxed."
chest:
  weight: 0.23
  relaxed_max: 1.0
  slim_penalty: 35.0
  oversized_max: 2.8
shoulder:
  weight: 0.21
length:
  weight: 0.13
hem:
  weight: 0.13
weight:
  mid_score: 75
  light_score: 80
interaction_adjustments:
  slim_light_penalty: 7
