name: vintage_90s
description: "A 90s-inspired fit—slightly boxy and midweight focus."

aspects:
  chest:
    # Mildly reduce chest weight influence (0.95×)
    weight_multiplier: 0.95
    # Increase relaxed gap by 1.0" for boxier chest
    relaxed_max_offset: 1.0

  shoulder:
    # More drop-shoulder for boxy silhouette
    drop_max_offset: 1.0

  length:
    # Inherit core

  hem:
    # Boxier hem gap: +0.8"
    flared_min_offset: 0.8

  sleeve:
    # Inherit core

  weight:
    # Favor midweight fabrics by shifting weight thresholds up slightly
    mid_max_offset: 0.5
    heavy_max_offset: 0.5

interaction_adjustments:
  # No change to interaction adjustments
